server:
  servlet:
    context-path:
spring:
  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      config:
#        import-check:
#          enabled: false
#        namespace: dev
#  config:
#    import: naocs:application.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: blog-serve
# Swagger配置
#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    email: xiaoymin@foxmail.com
#    concat: 八一菜刀
#    url: https://docs.xiaominfo.coma
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test:
#        group-name: 测试组
#        api-rule: package
#        api-rule-resources:
#          - com.zzt.blog.controller
# springdoc-openapi项目配置
# springdoc-openapi项目配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzt.blog.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-enums-package: com.zzt.blog.enums
  global-config:
    db-config:
      id-type: auto